package com.wedo.backend.task.service;
import com.wedo.backend.activity.entity.ActivityStatus; import com.wedo.backend.activity.service.*; import com.wedo.backend.common.error.*; import com.wedo.backend.group.entity.*; import com.wedo.backend.group.repository.GroupMembershipRepository; import com.wedo.backend.task.dto.*; import com.wedo.backend.task.entity.*; import com.wedo.backend.task.repository.*; import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional(readOnly=true) public class TaskService { private final M8ActivityAccessService access; private final GroupMembershipRepository memberships; private final TaskRepository tasks; private final TaskAssigneeRepository assignees; private final TaskStatusHistoryRepository histories; private final Clock clock; @org.springframework.beans.factory.annotation.Autowired(required=false) private org.springframework.context.ApplicationEventPublisher eventPublisher; public TaskService(M8ActivityAccessService access,GroupMembershipRepository memberships,TaskRepository tasks,TaskAssigneeRepository assignees,TaskStatusHistoryRepository histories,Clock clock){this.access=access;this.memberships=memberships;this.tasks=tasks;this.assignees=assignees;this.histories=histories;this.clock=clock;}
 @Transactional public TaskResponse create(UUID activityId,UUID actor,CreateTaskRequest r){M8ActivityAccess a=mutable(activityId,actor);Instant now=clock.instant();TaskEntity task=tasks.save(new TaskEntity(UUID.randomUUID(),activityId,actor,r.title().trim(),normalize(r.description()),r.dueAt(),now));replaceAssignees(task,a.activity().getGroupId(),actor,r.assigneeUserIds(),now);histories.save(new TaskStatusHistoryEntity(UUID.randomUUID(),task.getId(),null,TaskStatus.TODO,actor,now));publishTaskEvent(task,a.activity().getGroupId(),actor,"TASK_ASSIGNED",assignees.findByTaskId(task.getId()).stream().map(TaskAssigneeEntity::getUserId).toList(),now);return response(task,a,actor);}
 public List<TaskResponse> list(UUID activityId,UUID actor,TaskStatus status,boolean assignedToMe){M8ActivityAccess a=access.requireReadable(activityId,actor);return tasks.findByActivityIdOrderByCreatedAtDesc(activityId).stream().filter(t->status==null||t.getStatus()==status).filter(t->!assignedToMe||assignees.existsByTaskIdAndUserId(t.getId(),actor)).map(t->response(t,a,actor)).toList();}
 public TaskResponse get(UUID taskId,UUID actor){TaskEntity task=readable(taskId,actor);return response(task,access.requireReadable(task.getActivityId(),actor),actor);}
 @Transactional public TaskResponse update(UUID taskId,UUID actor,UpdateTaskRequest r){TaskEntity task=locked(taskId);M8ActivityAccess a=mutable(task.getActivityId(),actor);requireManager(task,a,actor);Set<UUID> previous=new HashSet<>(assignees.findByTaskId(taskId).stream().map(TaskAssigneeEntity::getUserId).toList());Instant now=clock.instant();task.update(r.title().trim(),normalize(r.description()),r.dueAt(),now);replaceAssignees(task,a.activity().getGroupId(),actor,r.assigneeUserIds(),now);List<UUID> added=assignees.findByTaskId(taskId).stream().map(TaskAssigneeEntity::getUserId).filter(id->!previous.contains(id)).toList();publishTaskEvent(task,a.activity().getGroupId(),actor,"TASK_ASSIGNED",added,now);return response(task,a,actor);}
 @Transactional public TaskResponse changeStatus(UUID taskId,UUID actor,UpdateTaskStatusRequest r){TaskEntity task=locked(taskId);M8ActivityAccess a=mutable(task.getActivityId(),actor);if(!statusActor(task,a,actor)&&!assignees.existsByTaskIdAndUserId(taskId,actor))throw new BusinessException(ErrorCode.TASK_UPDATE_NOT_ALLOWED);if(task.getStatus()!=r.status()){Instant now=clock.instant();TaskStatus from=task.changeStatus(r.status(),now);histories.save(new TaskStatusHistoryEntity(UUID.randomUUID(),taskId,from,r.status(),actor,now));Set<UUID> recipients=new LinkedHashSet<>();recipients.add(task.getCreatedBy());assignees.findByTaskId(taskId).stream().map(TaskAssigneeEntity::getUserId).forEach(recipients::add);recipients.remove(actor);publishTaskEvent(task,a.activity().getGroupId(),actor,"TASK_STATUS_CHANGED",List.copyOf(recipients),now);}return response(task,a,actor);}
 @Transactional public TaskResponse claim(UUID taskId,UUID actor){TaskEntity task=locked(taskId);M8ActivityAccess a=mutable(task.getActivityId(),actor);if(assignees.countByTaskId(taskId)>0)throw new BusinessException(ErrorCode.TASK_NOT_CLAIMABLE);requireActiveMember(a.activity().getGroupId(),actor);assignees.save(new TaskAssigneeEntity(UUID.randomUUID(),taskId,actor,actor,clock.instant()));return response(task,a,actor);}
 @Transactional public void delete(UUID taskId,UUID actor){TaskEntity task=locked(taskId);M8ActivityAccess a=mutable(task.getActivityId(),actor);if(!manager(task,a,actor))throw new BusinessException(ErrorCode.TASK_DELETE_NOT_ALLOWED);tasks.delete(task);}
 private TaskEntity readable(UUID id,UUID actor){TaskEntity t=tasks.findById(id).orElseThrow(()->new BusinessException(ErrorCode.TASK_NOT_FOUND));access.requireReadable(t.getActivityId(),actor);return t;} private TaskEntity locked(UUID id){return tasks.findByIdForUpdate(id).orElseThrow(()->new BusinessException(ErrorCode.TASK_NOT_FOUND));} private M8ActivityAccess mutable(UUID id,UUID actor){M8ActivityAccess a=access.requireMutable(id,actor);if(a.activity().getStatus()==ActivityStatus.COMPLETED||a.activity().getStatus()==ActivityStatus.CANCELLED)throw new BusinessException(ErrorCode.ACTIVITY_CLOSED);return a;}
 private boolean manager(TaskEntity t,M8ActivityAccess a,UUID actor){GroupRole role=a.groupAccess().membership().getRole();return actor.equals(t.getCreatedBy())||role==GroupRole.OWNER||role==GroupRole.ADMIN;} private boolean statusActor(TaskEntity t,M8ActivityAccess a,UUID actor){return manager(t,a,actor)||actor.equals(a.activity().getCreatedBy());} private void requireManager(TaskEntity t,M8ActivityAccess a,UUID actor){if(!manager(t,a,actor))throw new BusinessException(ErrorCode.TASK_UPDATE_NOT_ALLOWED);} private void requireActiveMember(UUID groupId,UUID userId){if(memberships.findFirstByGroupIdAndUserIdAndStatus(groupId,userId,GroupMembershipStatus.ACTIVE).isEmpty())throw new BusinessException(ErrorCode.GROUP_MEMBER_NOT_FOUND);}
 private void publishTaskEvent(TaskEntity task,UUID groupId,UUID actor,String eventType,List<UUID> recipients,Instant now){if(eventPublisher==null||recipients.isEmpty())return;eventPublisher.publishEvent(new com.wedo.backend.notification.event.NotificationDomainEvent(eventType+":"+task.getId()+":"+now.toEpochMilli(),eventType,"TASK","NORMAL",false,actor,groupId,recipients,eventType.equals("TASK_ASSIGNED")?"Công việc được giao":"Trạng thái công việc đã thay đổi",task.getTitle(),"TASK",task.getId(),"/activities/detail",Map.of("groupId",groupId.toString(),"activityId",task.getActivityId().toString()),now));}
 private void replaceAssignees(TaskEntity task,UUID groupId,UUID actor,List<UUID> requested,Instant now){Set<UUID> desired=requested==null?Set.of():new LinkedHashSet<>(requested);for(UUID user:desired)requireActiveMember(groupId,user);for(TaskAssigneeEntity old:assignees.findByTaskId(task.getId()))if(!desired.contains(old.getUserId()))assignees.delete(old);for(UUID user:desired)if(!assignees.existsByTaskIdAndUserId(task.getId(),user))assignees.save(new TaskAssigneeEntity(UUID.randomUUID(),task.getId(),user,actor,now));} private String normalize(String value){return value==null?null:value.trim();}
 private TaskResponse response(TaskEntity task,M8ActivityAccess a,UUID actor){List<UUID> assigned=assignees.findByTaskId(task.getId()).stream().map(TaskAssigneeEntity::getUserId).toList();boolean mutable=a.groupAccess().group().getStatus()!=GroupStatus.ARCHIVED&&a.activity().getStatus()!=ActivityStatus.COMPLETED&&a.activity().getStatus()!=ActivityStatus.CANCELLED;boolean manager=manager(task,a,actor);return new TaskResponse(task.getId(),task.getActivityId(),task.getCreatedBy(),task.getTitle(),task.getDescription(),task.getStatus(),task.getDueAt(),assigned,histories.findByTaskIdOrderByCreatedAtAsc(task.getId()).stream().map(TaskStatusHistoryResponse::of).toList(),new TaskPermissions(mutable&&manager,mutable&&manager,mutable&&assigned.isEmpty(),mutable&&(statusActor(task,a,actor)||assigned.contains(actor)),mutable&&manager));}
}
