package com.wedo.backend.poll.service;

import com.wedo.backend.activity.service.M8ActivityAccess;
import com.wedo.backend.activity.service.M8ActivityAccessService;
import com.wedo.backend.common.error.*;
import com.wedo.backend.group.entity.GroupRole;
import com.wedo.backend.group.repository.GroupMembershipRepository;
import com.wedo.backend.poll.dto.*;
import com.wedo.backend.poll.entity.*;
import com.wedo.backend.poll.repository.*;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional(readOnly = true)
public class PollService {
 private final M8ActivityAccessService access; private final PollRepository polls; private final PollOptionRepository options; private final PollVoteRepository votes; private final PollVoteChoiceRepository choices; private final Clock clock;
 @Autowired(required=false) private ApplicationEventPublisher eventPublisher;
 @Autowired(required=false) private GroupMembershipRepository memberships;
 public PollService(M8ActivityAccessService access,PollRepository polls,PollOptionRepository options,PollVoteRepository votes,PollVoteChoiceRepository choices,Clock clock){this.access=access;this.polls=polls;this.options=options;this.votes=votes;this.choices=choices;this.clock=clock;}
 @Transactional public PollResponse create(UUID activityId,UUID actor,CreatePollRequest request){M8ActivityAccess a=access.requireMutable(activityId,actor); validateCreate(request); Instant now=clock.instant(); PollEntity poll=polls.save(new PollEntity(UUID.randomUUID(),activityId,actor,request.question().trim(),request.pollType(),request.allowMemberAddOption(),request.maxSelections(),request.voteVisibility(),request.resultVisibility(),request.deadlineAt(),now)); int order=0; for(String text:request.options()) options.save(new PollOptionEntity(UUID.randomUUID(),poll.getId(),text.trim(),order++,actor,now)); publishPollEvent(poll,a.activity().getGroupId(),actor,"POLL_CREATED",now); return response(poll,actor);}
 public List<PollResponse> list(UUID activityId,UUID actor){access.requireReadable(activityId,actor); return polls.findByActivityIdOrderByCreatedAtDesc(activityId).stream().map(p->{closeIfDue(p);return response(p,actor);}).toList();}
 public PollResponse get(UUID pollId,UUID actor){PollEntity p=readable(pollId,actor); closeIfDue(p);return response(p,actor);}
 @Transactional public PollResponse vote(UUID pollId,UUID actor,VotePollRequest request){PollEntity p=lockedReadable(pollId,actor); requireOpen(p); Set<UUID> ids=new LinkedHashSet<>(request.optionIds()); validateSelection(p,ids); Instant now=clock.instant(); PollVoteEntity ballot=votes.findByPollIdAndUserId(pollId,actor).orElseGet(()->votes.save(new PollVoteEntity(UUID.randomUUID(),pollId,actor,now))); choices.deleteByVoteId(ballot.getId()); for(UUID id:ids) choices.save(new PollVoteChoiceEntity(UUID.randomUUID(),ballot.getId(),id,now)); ballot.touch(now); return response(p,actor);}
 @Transactional public PollResponse addOption(UUID pollId,UUID actor,CreatePollOptionRequest request){PollEntity p=lockedReadable(pollId,actor); requireOpen(p); if(!p.isAllowMemberAddOption()&&!manager(p,actor))throw new BusinessException(ErrorCode.INSUFFICIENT_GROUP_PERMISSION); String text=request.text().trim(); if(options.findByPollIdOrderBySortOrderAsc(pollId).stream().anyMatch(o->o.getText().equals(text)))throw new BusinessException(ErrorCode.CONFLICT); options.save(new PollOptionEntity(UUID.randomUUID(),pollId,text,(int)options.countByPollId(pollId),actor,clock.instant()));return response(p,actor);}
 @Transactional public PollResponse updateOption(UUID pollId,UUID optionId,UUID actor,UpdatePollOptionRequest request){PollEntity p=lockedReadable(pollId,actor); requireOpen(p); PollOptionEntity o=option(pollId,optionId); if(!manager(p,actor)&&!actor.equals(o.getCreatedBy()))throw new BusinessException(ErrorCode.INSUFFICIENT_GROUP_PERMISSION); if(choices.countByOptionId(optionId)>0)throw new BusinessException(ErrorCode.POLL_OPTION_CHANGE_NOT_ALLOWED); o.update(request.text().trim());return response(p,actor);}
 @Transactional public void deleteOption(UUID pollId,UUID optionId,UUID actor){PollEntity p=lockedReadable(pollId,actor); requireOpen(p); PollOptionEntity o=option(pollId,optionId); if(!manager(p,actor)&&!actor.equals(o.getCreatedBy()))throw new BusinessException(ErrorCode.INSUFFICIENT_GROUP_PERMISSION); if(choices.countByOptionId(optionId)>0)throw new BusinessException(ErrorCode.POLL_OPTION_CHANGE_NOT_ALLOWED); options.delete(o);}
 @Transactional public PollResponse disableOption(UUID pollId,UUID optionId,UUID actor){PollEntity p=lockedReadable(pollId,actor); requireOpen(p); if(!manager(p,actor))throw new BusinessException(ErrorCode.INSUFFICIENT_GROUP_PERMISSION); option(pollId,optionId).disable();return response(p,actor);}
 @Transactional public PollResponse close(UUID pollId,UUID actor){PollEntity p=lockedReadable(pollId,actor); if(!manager(p,actor))throw new BusinessException(ErrorCode.INSUFFICIENT_GROUP_PERMISSION); closeIfDue(p); boolean wasOpen=p.getStatus()==PollStatus.OPEN; Instant now=clock.instant(); p.close(actor,now); if(wasOpen)publishPollEvent(p,access.requireReadable(p.getActivityId(),actor).activity().getGroupId(),actor,"POLL_CLOSED",now); return response(p,actor);}
 public List<PollVoterResponse> voters(UUID pollId,UUID actor){PollEntity p=readable(pollId,actor); closeIfDue(p); if(p.getVoteVisibility()!=VoteVisibility.PUBLIC)throw new BusinessException(ErrorCode.POLL_VOTERS_PRIVATE); Map<UUID,List<UUID>> result=new LinkedHashMap<>(); for(PollOptionEntity option:options.findByPollIdOrderBySortOrderAsc(pollId))result.put(option.getId(),new ArrayList<>()); for(PollVoteEntity vote:votes.findAll()){if(vote.getPollId().equals(pollId))for(PollVoteChoiceEntity choice:choices.findByVoteId(vote.getId()))result.get(choice.getOptionId()).add(vote.getUserId());} return result.entrySet().stream().map(e->new PollVoterResponse(e.getKey(),List.copyOf(e.getValue()))).toList();}
 private PollEntity readable(UUID pollId,UUID actor){PollEntity p=polls.findById(pollId).orElseThrow(()->new BusinessException(ErrorCode.POLL_NOT_FOUND));access.requireReadable(p.getActivityId(),actor);return p;} private PollEntity lockedReadable(UUID pollId,UUID actor){PollEntity p=polls.findByIdForUpdate(pollId).orElseThrow(()->new BusinessException(ErrorCode.POLL_NOT_FOUND));access.requireMutable(p.getActivityId(),actor);return p;}
 private void requireOpen(PollEntity p){if(p.closeIfDue(clock.instant()))polls.save(p);if(p.getStatus()!=PollStatus.OPEN)throw new BusinessException(p.getDeadlineAt()!=null&&!p.getDeadlineAt().isAfter(clock.instant())?ErrorCode.POLL_DEADLINE_PASSED:ErrorCode.POLL_CLOSED);} private void closeIfDue(PollEntity p){if(p.closeIfDue(clock.instant()))polls.save(p);} private PollOptionEntity option(UUID pollId,UUID optionId){return options.findById(optionId).filter(o->o.getPollId().equals(pollId)).orElseThrow(()->new BusinessException(ErrorCode.INVALID_POLL_SELECTION));}
 private boolean manager(PollEntity p,UUID actor){M8ActivityAccess a=access.requireReadable(p.getActivityId(),actor);GroupRole role=a.groupAccess().membership().getRole();return actor.equals(p.getCreatedBy())||role==GroupRole.OWNER||role==GroupRole.ADMIN;}
 private void publishPollEvent(PollEntity poll,UUID groupId,UUID actor,String eventType,Instant now){if(eventPublisher==null||memberships==null)return;List<UUID> recipients=memberships.findActiveMemberResponsesByGroupId(groupId).stream().map(com.wedo.backend.group.repository.GroupMemberProjection::getUserId).filter(id->!id.equals(actor)).toList();if(recipients.isEmpty())return;eventPublisher.publishEvent(new com.wedo.backend.notification.event.NotificationDomainEvent(eventType+":"+poll.getId(),eventType,"POLL","NORMAL",false,actor,groupId,recipients,eventType.equals("POLL_CREATED")?"Bình chọn mới":"Bình chọn đã đóng",poll.getQuestion(),"POLL",poll.getId(),"/activities/detail",Map.of("groupId",groupId.toString(),"activityId",poll.getActivityId().toString()),now));}
 private void validateCreate(CreatePollRequest r){if(r.pollType()==PollType.SINGLE_CHOICE&&r.maxSelections()!=null)throw new BusinessException(ErrorCode.INVALID_POLL_SELECTION);if(r.pollType()==PollType.MULTIPLE_CHOICE&&r.maxSelections()!=null&&r.maxSelections()>r.options().size())throw new BusinessException(ErrorCode.MAX_POLL_SELECTIONS_EXCEEDED);if(r.deadlineAt()!=null&&!r.deadlineAt().isAfter(clock.instant()))throw new BusinessException(ErrorCode.POLL_DEADLINE_PASSED);if(r.options().stream().map(s->s.trim().toLowerCase(Locale.ROOT)).distinct().count()!=r.options().size())throw new BusinessException(ErrorCode.CONFLICT);}
 private void validateSelection(PollEntity p,Set<UUID> ids){if(ids.isEmpty())throw new BusinessException(ErrorCode.INVALID_POLL_SELECTION);if(p.getPollType()==PollType.SINGLE_CHOICE&&ids.size()!=1)throw new BusinessException(ErrorCode.INVALID_POLL_SELECTION);if(p.getMaxSelections()!=null&&ids.size()>p.getMaxSelections())throw new BusinessException(ErrorCode.MAX_POLL_SELECTIONS_EXCEEDED);Map<UUID,PollOptionEntity> allowed=new HashMap<>();for(PollOptionEntity o:options.findByPollIdOrderBySortOrderAsc(p.getId()))allowed.put(o.getId(),o);for(UUID id:ids){PollOptionEntity o=allowed.get(id);if(o==null)throw new BusinessException(ErrorCode.INVALID_POLL_SELECTION);if(o.isDisabled())throw new BusinessException(ErrorCode.POLL_OPTION_DISABLED);}}
 private PollResponse response(PollEntity p,UUID actor){List<UUID> mine=votes.findByPollIdAndUserId(p.getId(),actor).map(v->choices.findByVoteId(v.getId()).stream().map(PollVoteChoiceEntity::getOptionId).toList()).orElse(List.of());boolean visible=p.getResultVisibility()==ResultVisibility.IMMEDIATE||p.getStatus()==PollStatus.CLOSED;boolean manager=manager(p,actor),open=p.getStatus()==PollStatus.OPEN;List<PollOptionResponse> os=options.findByPollIdOrderBySortOrderAsc(p.getId()).stream().map(o->{long count=choices.countByOptionId(o.getId());boolean editable=open&&count==0&&(manager||actor.equals(o.getCreatedBy()));return new PollOptionResponse(o.getId(),o.getText(),o.getSortOrder(),o.isDisabled(),o.getCreatedBy(),visible?count:0,editable,open&&manager&&!o.isDisabled(),editable);}).toList();return new PollResponse(p.getId(),p.getActivityId(),p.getCreatedBy(),p.getQuestion(),p.getPollType(),p.isAllowMemberAddOption(),p.getMaxSelections(),p.getVoteVisibility(),p.getResultVisibility(),p.getStatus(),p.getDeadlineAt(),p.getClosedAt(),p.getClosedBy(),os,mine,visible,new PollPermissions(open,open&&(p.isAllowMemberAddOption()||manager),open&&manager,p.getVoteVisibility()==VoteVisibility.PUBLIC));}
}
