package com.wedo.backend.activity.service;

import com.wedo.backend.activity.entity.*;
import com.wedo.backend.activity.repository.*;
import com.wedo.backend.common.test.AbstractPostgresIntegrationTest;
import com.wedo.backend.group.entity.*; import com.wedo.backend.group.event.GroupMembershipEndedEvent;
import com.wedo.backend.group.repository.*;
import com.wedo.backend.group.service.*;
import com.wedo.backend.user.entity.*;
import com.wedo.backend.user.repository.UserRepository;
import java.time.Instant; import java.util.*; import java.util.concurrent.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.transaction.PlatformTransactionManager; import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;

class ActivityMembershipLossTransactionIntegrationTest extends AbstractPostgresIntegrationTest {
 private static final Instant NOW=Instant.parse("2026-09-15T12:00:00Z");
 @Autowired GroupService groupService; @Autowired GroupBanService bans; @Autowired ActivityRsvpService rsvp; @Autowired ActivityMembershipLossProcessor processor; @Autowired PlatformTransactionManager transactionManager; @Autowired GroupRepository groups; @Autowired GroupMembershipRepository memberships; @Autowired UserRepository users; @Autowired ActivityRepository activities; @Autowired ActivityParticipantRepository participants; @Autowired ActivityRsvpHistoryRepository histories; @Autowired GroupBanRepository banRepository;
 @Test void leaveCommit_afterCommitProcessorCleansGoingAndPromotesWaiter(){Fixture f=fixture();groupService.leave(f.groupId,f.target);assertEquals(GroupMembershipStatus.LEFT,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertCleanup(f);}
 @Test void kickCommit_afterCommitProcessorCleansGoingAndPromotesWaiter(){Fixture f=fixture();groupService.kick(f.groupId,f.target,f.owner);assertEquals(GroupMembershipStatus.KICKED,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertCleanup(f);}
 @Test void banCommit_afterCommitProcessorCleansGoingAndPromotesWaiter(){Fixture f=fixture();bans.banMember(f.groupId,f.target,f.owner,"reason");assertEquals(GroupMembershipStatus.BANNED,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertTrue(banRepository.existsByGroupIdAndUserIdAndUnbannedAtIsNull(f.groupId,f.target));assertCleanup(f);}
 @Test void duplicateTerminalEvent_isIdempotent(){Fixture f=fixture();GroupMembershipEndedEvent event=new GroupMembershipEndedEvent(f.targetMembership,f.groupId,f.target,GroupRole.MEMBER,GroupMembershipStatus.LEFT,NOW);processor.processOne(event,f.activityId);processor.processOne(event,f.activityId);assertCleanup(f);}
 @Test void staleTerminalEvent_doesNotOverwriteNewerParticipant(){Fixture f=fixture();ActivityParticipantEntity target=participants.findByActivityIdAndUserId(f.activityId,f.target).orElseThrow();target.changeTo(ActivityRsvpStatus.MAYBE,null,NOW.plusSeconds(60));participants.saveAndFlush(target);processor.processOne(new GroupMembershipEndedEvent(f.targetMembership,f.groupId,f.target,GroupRole.MEMBER,GroupMembershipStatus.LEFT,NOW),f.activityId);assertEquals(ActivityRsvpStatus.MAYBE,participants.findByActivityIdAndUserId(f.activityId,f.target).orElseThrow().getRsvpStatus());assertEquals(0,histories.findAll().stream().filter(h->h.getActivityId().equals(f.activityId)).count());}
 @Test void rollbackAfterProductionLeavePublish_doesNotRunAfterCommitCleanup(){Fixture f=fixture();new TransactionTemplate(transactionManager).executeWithoutResult(s->{groupService.leave(f.groupId,f.target);s.setRollbackOnly();});assertEquals(GroupMembershipStatus.ACTIVE,memberships.findById(f.targetMembership).orElseThrow().getStatus());ActivityParticipantEntity target=participants.findByActivityIdAndUserId(f.activityId,f.target).orElseThrow();ActivityParticipantEntity waiter=participants.findByActivityIdAndUserId(f.activityId,f.waiter).orElseThrow();assertEquals(ActivityRsvpStatus.GOING,target.getRsvpStatus());assertNull(target.getWaitlistSequence());assertEquals(ActivityRsvpStatus.WAITLIST,waiter.getRsvpStatus());assertEquals(1L,waiter.getWaitlistSequence());assertEquals(0,histories.findAll().stream().filter(h->h.getActivityId().equals(f.activityId)).count());}
 @Test void concurrentGoingRsvpAndLeave_cannotResurrectEndedMember(){Fixture f=fixture();race(f,()->groupService.leave(f.groupId,f.target));assertEquals(GroupMembershipStatus.LEFT,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertCleanup(f);}
 @Test void concurrentGoingRsvpAndKick_cannotResurrectEndedMember(){Fixture f=fixture();race(f,()->groupService.kick(f.groupId,f.target,f.owner));assertEquals(GroupMembershipStatus.KICKED,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertCleanup(f);}
 @Test void concurrentGoingRsvpAndBan_cannotResurrectEndedMember(){Fixture f=fixture();race(f,()->bans.banMember(f.groupId,f.target,f.owner,"race"));assertEquals(GroupMembershipStatus.BANNED,memberships.findById(f.targetMembership).orElseThrow().getStatus());assertCleanup(f);}
 @Test void concurrentLeaveAndKick_releaseOnlyOneSlotAndPromoteFifoOnce(){Fixture f=fixture();ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);try{Future<Throwable> leave=pool.submit(()->terminalWorker(ready,start,()->groupService.leave(f.groupId,f.target)));Future<Throwable> kick=pool.submit(()->terminalWorker(ready,start,()->groupService.kick(f.groupId,f.target,f.owner)));assertTrue(ready.await(10,TimeUnit.SECONDS));start.countDown();Throwable left=leave.get(30,TimeUnit.SECONDS),kicked=kick.get(30,TimeUnit.SECONDS);assertTrue((left==null)^(kicked==null),()->"exactly one terminal mutation must commit: leave="+left+", kick="+kicked);assertTrue((left==null||left instanceof com.wedo.backend.common.error.BusinessException)&&(kicked==null||kicked instanceof com.wedo.backend.common.error.BusinessException));assertCleanup(f);}catch(Exception e){throw new AssertionError(e);}finally{pool.shutdownNow();try{assertTrue(pool.awaitTermination(10,TimeUnit.SECONDS));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}}}
 private void assertCleanup(Fixture f){ActivityParticipantEntity departed=participants.findByActivityIdAndUserId(f.activityId,f.target).orElseThrow();ActivityParticipantEntity waiter=participants.findByActivityIdAndUserId(f.activityId,f.waiter).orElseThrow();assertEquals(ActivityRsvpStatus.NOT_GOING,departed.getRsvpStatus());assertNull(departed.getWaitlistSequence());assertEquals(ActivityRsvpStatus.GOING,waiter.getRsvpStatus());assertNull(waiter.getWaitlistSequence());assertEquals(2,histories.findAll().stream().filter(h->h.getActivityId().equals(f.activityId)).count());}
 private void race(Fixture f,Runnable terminal){ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);try{Future<Throwable>a=pool.submit(()->{ready.countDown();start.await();try{rsvp.changeRsvp(f.activityId,f.target,new com.wedo.backend.activity.dto.ChangeRsvpRequest(ActivityRsvpStatus.GOING));return null;}catch(Throwable t){return t;}});Future<Throwable>b=pool.submit(()->{ready.countDown();start.await();try{terminal.run();return null;}catch(Throwable t){return t;}});assertTrue(ready.await(10,TimeUnit.SECONDS));start.countDown();Throwable first=a.get(30,TimeUnit.SECONDS),second=b.get(30,TimeUnit.SECONDS);assertNull(second,()->"terminal worker failed: "+second);assertTrue(first==null||first instanceof com.wedo.backend.common.error.BusinessException,()->"unexpected RSVP failure: "+first);}catch(Exception e){throw new AssertionError(e);}finally{pool.shutdownNow();try{assertTrue(pool.awaitTermination(10,TimeUnit.SECONDS));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}}}
 private Throwable terminalWorker(CountDownLatch ready,CountDownLatch start,Runnable action){try{ready.countDown();start.await();action.run();return null;}catch(Throwable t){return t;}}
 private Fixture fixture(){UUID owner=user(),target=user(),waiter=user(),groupId=UUID.randomUUID(),activityId=UUID.randomUUID();groups.save(new GroupEntity(groupId,"g",null,null,GroupStatus.ACTIVE,owner,NOW,NOW));memberships.save(new GroupMembershipEntity(UUID.randomUUID(),groupId,owner,GroupRole.OWNER,GroupMembershipStatus.ACTIVE,NOW,null));UUID mid=UUID.randomUUID();memberships.save(new GroupMembershipEntity(mid,groupId,target,GroupRole.MEMBER,GroupMembershipStatus.ACTIVE,NOW,null));memberships.save(new GroupMembershipEntity(UUID.randomUUID(),groupId,waiter,GroupRole.MEMBER,GroupMembershipStatus.ACTIVE,NOW,null));activities.save(new ActivityEntity(activityId,groupId,owner,"a",null,ActivityStatus.CONFIRMED,NOW.plusSeconds(3600),null,"UTC",new ActivityLocation("PHYSICAL","v",null,null,null),1,NOW,NOW));participants.save(new ActivityParticipantEntity(UUID.randomUUID(),activityId,target,ActivityRsvpStatus.GOING,null,NOW,NOW,NOW));participants.save(new ActivityParticipantEntity(UUID.randomUUID(),activityId,waiter,ActivityRsvpStatus.WAITLIST,1L,NOW,NOW,NOW));return new Fixture(groupId,activityId,target,waiter,mid,owner);}
 private UUID user(){UUID id=UUID.randomUUID();users.save(new UserEntity(id,"m"+id+"@t.local","m"+id.toString().substring(0,8),"M",UserStatus.ACTIVE,NOW,NOW));return id;} private record Fixture(UUID groupId,UUID activityId,UUID target,UUID waiter,UUID targetMembership,UUID owner){}
}
