package com.wedo.backend.group.entity;

public enum GroupActivityAction {
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_SETTINGS_UPDATED,
    GROUP_ADMIN_PROMOTED,
    GROUP_ADMIN_DEMOTED,
    GROUP_MEMBER_LEFT,
    GROUP_MEMBER_KICKED,
    GROUP_OWNERSHIP_TRANSFERRED
}
