spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  health:
    redis:
      enabled: false

security:
  jwt:
    secret-base64: HtYDoxLoUE6DB2ghGul6hVTMTMpg0ysFkJPvuDWf8aU=
    access-token-ttl: 15m
