spring:
  application:
    name: wedo-backend

  profiles:
    default: local

server:
  port: 8080

security:
  jwt:
    secret-base64: ${WEDO_JWT_SECRET_BASE64}
    access-token-ttl: ${WEDO_JWT_ACCESS_TOKEN_TTL:15m}
