spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  health:
    redis:
      enabled: false

security:
  jwt:
    secret-base64: HtYDoxLoUE6DB2ghGul6hVTMTMpg0ysFkJPvuDWf8aU=
    access-token-ttl: 15m
  auth-token:
    pepper-base64: t6rY9uI2oP5aD8k7e8pP5Fj9sW2mN1bV4cZ0xL8qJ3h=
  profile-completion-token:
    secret-base64: q9W8eR7tY6uI5oP4aD3fG2hJ1kL0zX9cV8bN7mQ6wE5=
    ttl: 15m
